# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               William Clarke's Blog
tagline:             'wmmc.github.io'
description:         'Ramblings from <a href="http://wmmclarke.com" target="_blank">William Clarke.'
baseurl:             'wmmc.github.io/blog'
url:                 'http://wmmc.github.io'
paginate:            5

# About/contact
author:
  name:              William Clarke
  url:               http://wmmclarke.com
  email:             wmmclarke@gmail.com
