# Dependencies
markdown:            kramdown
highlighter:         pygments
kramdown:
  input: GFM
  use_coderay: true
  coderay:
    coderay_line_numbers: nil

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               William Clarke's Blog
tagline:             'wmmc.github.io'
description:         'Ramblings from <a href="http://wmmclarke.com" target="_blank">William Clarke.'
baseurl:             ''
url:                 'http://wmmc.github.io'
paginate:            5

# About/contact
author:
  name:              William Clarke
  url:               http://wmmclarke.com
  email:             wmmclarke@gmail.com
