# Dependencies
markdown:            kramdown
highlighter:         pygments

syntax_highlighter: coderay

plugins: [jekyll-paginate]

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               William Clarke's Blog
tagline:             '<a href="http://wmmclarke.com" >wmmclarke.com</a>'
description:         'Ramblings from <a href="http://wmmclarke.com" target="_blank">William Clarke.</a>'
baseurl:             ''
url:                 'http://blog.wmmclarke.com'
paginate:            10

# About/contact
author:
  name:              William Clarke
  url:               http://wmmclarke.com
  email:             wmmclarke@gmail.com
